# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import Bus_Monitor_API_pb2 as proto_dot_Bus__Monitor__API__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/Bus_Monitor_API_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Bus_Monitor_APIStub(object):
    """---------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PassThru = channel.unary_unary(
                '/ni_bus_monitor_api.Bus_Monitor_API/PassThru',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.PassThruRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.PassThruReply.FromString,
                _registered_method=True)
        self.GetStreamingFilter = channel.unary_unary(
                '/ni_bus_monitor_api.Bus_Monitor_API/GetStreamingFilter',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.GetStreamingFilterRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.GetStreamingFilterReply.FromString,
                _registered_method=True)
        self.SetStreamingFilter = channel.unary_unary(
                '/ni_bus_monitor_api.Bus_Monitor_API/SetStreamingFilter',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.SetStreamingFilterRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.SetStreamingFilterReply.FromString,
                _registered_method=True)
        self.ResetStreamingFilter = channel.unary_unary(
                '/ni_bus_monitor_api.Bus_Monitor_API/ResetStreamingFilter',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.ResetStreamingFilterRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.ResetStreamingFilterReply.FromString,
                _registered_method=True)
        self.InitializeSettings = channel.unary_unary(
                '/ni_bus_monitor_api.Bus_Monitor_API/InitializeSettings',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.InitializeSettingsRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.InitializeSettingsReply.FromString,
                _registered_method=True)
        self.StopProcess = channel.unary_unary(
                '/ni_bus_monitor_api.Bus_Monitor_API/StopProcess',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.StopProcessRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.StopProcessReply.FromString,
                _registered_method=True)
        self.StreamBus = channel.unary_stream(
                '/ni_bus_monitor_api.Bus_Monitor_API/StreamBus',
                request_serializer=proto_dot_Bus__Monitor__API__pb2.StreamBusRequest.SerializeToString,
                response_deserializer=proto_dot_Bus__Monitor__API__pb2.StreamBusReply.FromString,
                _registered_method=True)


class Bus_Monitor_APIServicer(object):
    """---------------------------------------------------------------------

    """

    def PassThru(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamingFilter(self, request, context):
        """Pushes a RAW CAN frame directly to the bus.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStreamingFilter(self, request, context):
        """Get the current engine filter settings.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetStreamingFilter(self, request, context):
        """Set the current engine filter settings.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeSettings(self, request, context):
        """Reset the current engine filter settings to default values.

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopProcess(self, request, context):
        """Sets the XNET settings for the port:
        -CAN Port
        -Baud rates
        -Termination

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Bus_Monitor_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PassThru': grpc.unary_unary_rpc_method_handler(
                    servicer.PassThru,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.PassThruRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.PassThruReply.SerializeToString,
            ),
            'GetStreamingFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamingFilter,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.GetStreamingFilterRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.GetStreamingFilterReply.SerializeToString,
            ),
            'SetStreamingFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStreamingFilter,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.SetStreamingFilterRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.SetStreamingFilterReply.SerializeToString,
            ),
            'ResetStreamingFilter': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetStreamingFilter,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.ResetStreamingFilterRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.ResetStreamingFilterReply.SerializeToString,
            ),
            'InitializeSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeSettings,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.InitializeSettingsRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.InitializeSettingsReply.SerializeToString,
            ),
            'StopProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.StopProcess,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.StopProcessRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.StopProcessReply.SerializeToString,
            ),
            'StreamBus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBus,
                    request_deserializer=proto_dot_Bus__Monitor__API__pb2.StreamBusRequest.FromString,
                    response_serializer=proto_dot_Bus__Monitor__API__pb2.StreamBusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ni_bus_monitor_api.Bus_Monitor_API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ni_bus_monitor_api.Bus_Monitor_API', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bus_Monitor_API(object):
    """---------------------------------------------------------------------

    """

    @staticmethod
    def PassThru(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/PassThru',
            proto_dot_Bus__Monitor__API__pb2.PassThruRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.PassThruReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamingFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/GetStreamingFilter',
            proto_dot_Bus__Monitor__API__pb2.GetStreamingFilterRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.GetStreamingFilterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStreamingFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/SetStreamingFilter',
            proto_dot_Bus__Monitor__API__pb2.SetStreamingFilterRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.SetStreamingFilterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetStreamingFilter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/ResetStreamingFilter',
            proto_dot_Bus__Monitor__API__pb2.ResetStreamingFilterRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.ResetStreamingFilterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/InitializeSettings',
            proto_dot_Bus__Monitor__API__pb2.InitializeSettingsRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.InitializeSettingsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/StopProcess',
            proto_dot_Bus__Monitor__API__pb2.StopProcessRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.StopProcessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ni_bus_monitor_api.Bus_Monitor_API/StreamBus',
            proto_dot_Bus__Monitor__API__pb2.StreamBusRequest.SerializeToString,
            proto_dot_Bus__Monitor__API__pb2.StreamBusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
